### ISSUE TITLE
Option to skip header

### ISSUE THREAD

**Issue by nerdstep** [bartoszgolebiowski/zod-csv#1]
@bartoszgolebiowski would it be possible to support an option to skip reading the header?

my current use-case is reading a file stream line by line and wanting to parse each line individually.

**Comment by nerdstep** [comment]
that said, maybe what I'm really asking for is the ability to parse a file stream... but perhaps that is outside of the scope for what you intend this project to do?

**Comment by bartoszgolebiowski** [comment]
@nerdstep 
Streaming is an amazing missing feature for sure, but I am not sure how to do it for both node and browser. This is an interesting implementation of how to split CSV files. I think I would do something similar here. https://github.com/alex-murashkin/csv-split-stream#readme

**Comment by bartoszgolebiowski** [comment]
Maybe to resolve this issue we should consider adding a new method to check if **row** is valid against **schema**.
What do you think, is it sufficient for you @nerdstep

**Comment by nerdstep** [comment]
@bartoszgolebiowski -- I think streaming can be achieved in both node and browser, since the browser also supports a [Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API). The Papa Parse library [does this too](https://www.papaparse.com/#stream).

That said, if you wanted to keep this library small and avoid those implementation details, then a row validation method would make sense.

**Comment by bartoszgolebiowski** [comment]
https://github.com/bartoszgolebiowski/zod-csv/pull/2

This is a draft, I am open to naming, typing, and other suggestions!

**Comment by bartoszgolebiowski** [comment]
I introduced a new method: https://github.com/bartoszgolebiowski/zod-csv/blob/main/src/csv.ts#L173
Here is some basic usage: https://github.com/bartoszgolebiowski/zod-csv/blob/main/src/csv.test.ts#L390

**Comment by nerdstep** [comment]
nice work and thanks for the quick turnaround!
