### ISSUE TITLE
How to handle "," charakter within string value 

### ISSUE THREAD

**Issue by bartoszgolebiowski** [bartoszgolebiowski/zod-csv#3]
This is common usage
```js
    it("should return no errors, headers and rows from CSV string for schema with required fields", () => {
        const csv = `name,age
  John,20
  Doe,30`;
        const schema1 = z.object({
            name: zcsv.string(),
            age: zcsv.number(),
        });
        const result = parseCSVContent(csv, schema1);
        expect(result.header).toEqual(["name", "age"]);
        expect(result.validRows).toStrictEqual([
            { name: "John", age: 20 },
            { name: "Doe", age: 30 },
        ]);
        expect(result.success).toEqual(true);
        //@ts-expect-error - when success is true, errors are undefined
        expect(result.errors).toEqual(undefined);
    });
 ```
 
 But what if we want to pass **"John, thinker"**. Right now it will split this string value. 
 
 ```js
    it("should return no errors, headers and rows from CSV string for schema with required fields", () => {
        const csv = `name,age
  **"John, thinker"**,20
  Doe,30`;
        const schema1 = z.object({
            name: zcsv.string(),
            age: zcsv.number(),
        });
        const result = parseCSVContent(csv, schema1);
        expect(result.header).toEqual(["name", "age"]);
        expect(result.validRows).toStrictEqual([
            { name: "John", age: 20 },
            { name: "Doe", age: 30 },
        ]);
        expect(result.success).toEqual(true);
        //@ts-expect-error - when success is true, errors are undefined
        expect(result.errors).toEqual(undefined);
    });
 ```
 
 We should handle it!

**Comment by nerdstep** [comment]
I think this also raises another issue, which is that in some CSVs you may have fields escaped, e.g. `"John Doe", "30"`.

It might make sense to expose some options so that escape, delimiter, newline, etc. characters can be customized.

**Comment by bartoszgolebiowski** [comment]
Reinventing the wheel is not a good idea. I think we can reuse this simple lib to parse CSV string row.

- https://www.npmjs.com/package/papaparse is an amazing library, but it adds a lot of bundle size. Making it an external dependency is not a good idea, people who will use this library want a solution that just works without any additional steps. (Zod library is mandatory in all circumstances) It would be fantastic to just import _parse_ method and remove all other code, but I could not do that.  https://bundlephobia.com/package/papaparse-min@5.3.2

- https://www.npmjs.com/package/csv-string is another possibility, it supports line-by-line and streaming. I am considering in the future add streaming API to validate CSV against Zod schema so I can also utilize it later. https://bundlephobia.com/package/csv-string@4.1.1

Right now I choose [csv-string](https://www.npmjs.com/package/csv-string), maybe I will create some kind of interface to make it easy to replace it with for example [Papaparse](https://www.npmjs.com/package/papaparse).

**Comment by bartoszgolebiowski** [comment]
https://github.com/bartoszgolebiowski/zod-csv/pull/5

**Comment by nerdstep** [comment]
Nice! Yeah I agree with not reinventing the wheel, and `csv-string` seems like a reasonable choice here.
