### ISSUE TITLE
Support trailing `\n` character

### ISSUE THREAD

**Issue by johanneskares** [bartoszgolebiowski/zod-csv#4]
My CSV has a trailing `\n` and I had to remove it like this

```typescript
let csv = "...\n"
if (csv.endsWith("\n")) {
    csv = csv.slice(0, -1);
}
```

It would be fantastic if the library supported it out of the box.

**Comment by bartoszgolebiowski** [comment]
@johanneskares are you parsing the whole CSV file as a string and having some issues with the empty last row, am I right?

**Comment by johanneskares** [comment]
yes, correct!

Great lib, btw, saved me a lot of time!

**Comment by bartoszgolebiowski** [comment]
This issue should be resolved here: https://github.com/bartoszgolebiowski/zod-csv/pull/5 
https://github.com/bartoszgolebiowski/zod-csv/blob/main/src/csv.test.ts#L566
